# Generated by Django 2.0 on 2018-11-19 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('REST_API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='owner',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='REST_API.UserAccount'),
            preserve_default=False,
        ),
    ]
